eclipse-jkube/jkube-integration-tests

.github/workflows/integration-tests.yml, README.md, it/pom.xml, it/src/test/java/org/eclipse/jkube/integrationtests/Locks.java, it/src/test/java/org/eclipse/jkube/integrationtests/OpenShift.java, it/src/test/java/org/eclipse/jkube/integrationtests/maven/BaseMavenCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/na7ive/QuarkusNativeK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/Quarkus.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteDockerITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigOcITCase.java, pom.xml, projects-to-be-tested/quarkus/native/pom.xml, projects-to-be-tested/quarkus/native/src/main/java/org/eclipse/jkube/integrationtests/quarkus/na7ive/NativeResource.java, projects-to-be-tested/quarkus/native/src/main/java/org/eclipse/jkube/integrationtests/quarkus/na7ive/NativeService.java, projects-to-be-tested/quarkus/native/src/main/resources/native.json
Tests are now separated into different group in order to avoid hogging all woker's resources.
Once this one is merged, workflows in eclipse/jkube should be updated accordingly. I'll open a PR there too.
=> feature: Quarkus native + performance improvements + grouping

.github/workflows/integration-tests.yml, it/src/test/java/org/eclipse/jkube/integrationtests/assertions/KubernetesClientAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/assertions/PodAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/Thorntail.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/Vertx.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfig.java
Some integration tests fail in OpenShift 3.11 due to `DiskPressue`.
After analyzing and evaluating, tests suites that download more than one image (`other`) are the ones that will most probably be hit by this problem.
Although diagnostics show that there's still plenty of space and inodes free, it seems that there is some threshold (that can't be configured easily) that is surpassed, triggering the error.
In order to prevent this from happening, space is freed in the VM before invoking the test suite.
These changes should be propagated to https://github.com/eclipse/jkube/ integration-tests workflow > https://github.com/eclipse/jkube/pull/89
=> fix: Free up space in VM

pom.xml
Must check that quarkus-native integration tests are actually running (they should take something more than a couple of seconds ;) )
Tests are running (and passing :relieved:) now:
https://github.com/jkubeio/jkube-integration-tests/pull/22/checks?check_run_id=490658683#step:7:1168
https://github.com/jkubeio/jkube-integration-tests/pull/22/checks?check_run_id=490658737#step:7:1168
=> fix: typo in quarkus-native Maven profile

.github/workflows/windows-tests.yml, it/pom.xml, it/src/test/java/org/eclipse/jkube/integrationtests/Tags.java, it/src/test/java/org/eclipse/jkube/integrationtests/docker/RegistryExtension.java, it/src/test/java/org/eclipse/jkube/integrationtests/maven/BaseMavenCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteDockerITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/windows/WindowsITCase.java, pom.xml, projects-to-be-tested/windows/pom.xml, projects-to-be-tested/windows/src/main/java/org/eclipse/jkube/integrationtests/windows/SimpleApplication.java
There's no easy solution to add complete e2e tests for Windows Server 2019 (ephemeral k8s cluster).
Hyper-V is not enabled in GH Actions and enabling requires a VM restart which makes the GH Runner loose the connection to the VM.
Minikube with Virtualbox is not an option either, as it requires vt-x to be enabled (which isn't).
Trying to enable Linux container support doesn't work well and relies on experimental features (lcow project has been archived too), so running alternatives to Minikube (k3s, MicroK8s, etc.) is also impossible.
Current PR will create a Windows Container compatible Docker image and test resource generation.
Tested Eclipse JKube Features:
- build (k8s)
- push (k8s)
- resource (k8s & oc)
- helm (k8s & oc)
Relates to: eclipse/jkube#131
=> feature: Windows specific cases (No cluster support)

it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java
This PR adds end2end test for k8s and oc log in vertex-simplest test suites.
=>  E2E: Implement k8s|oc:log test in vertx-simplest test suites

it/src/test/java/org/eclipse/jkube/integrationtests/windows/WindowsITCase.java, projects-to-be-tested/windows/pom.xml
This parses the Dockerfile to see where the COPY instruction is reading files from.
This allows to verify that the files exist in that directory in a non-hard-coded way.
=> feat: windows test verifies docker assembly has files in specified directory

it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigOcITCase.java, pom.xml
- Test is compliant for new updated base images (https://github.com/eclipse/jkube/pull/206)
- Service edited and switched to NodePort to verify port response
- Added k8s:log goal verifications
- Updated Kubernetes-Client to 4.9.2 (latest stable)
Relates to:
- https://github.com/eclipse/jkube/pull/206 < **n.b. Tests will only pass when this is merged**
- https://github.com/eclipse/jkube/issues/183
=> feat: Improved webapp zero-config tests

projects-to-be-tested/wildflyswarm/rest/pom.xml
Remove no longer needed workaround for WildFlySwarm E2E test after fix in https://github.com/eclipse/jkube/pull/209
=> fix: remove no longer required workaround config for WilFlySwarm

it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/Jetty.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyOcITCase.java, pom.xml, projects-to-be-tested/webapp/jetty/pom.xml, projects-to-be-tested/webapp/jetty/src/main/resources/META-INF/jetty-logging.properties, projects-to-be-tested/webapp/jetty/src/main/webapp/index.html
Relates to:
- eclipse/jkube#210
- eclipse/jkube#183
=> feat: E2E tests for webapp-jetty

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteDockerITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteK8sITCase.java
The PR (https://github.com/eclipse/jkube/pull/214) for Karaf Generator fixed some problems with assemblies.
Our current assertions are wrong. This PR fixes assertions to verify valid expected output.
=> fix: Fix wrong assembly assertions after fixes provided by Karaf implementation

.github/workflows/e2e-tests.yml, it/src/test/java/org/eclipse/jkube/integrationtests/OpenShift.java, it/src/test/java/org/eclipse/jkube/integrationtests/assertions/KubernetesClientAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/Vertx.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/Jetty.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcDockerModeITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarmOcITCase.java, projects-to-be-tested/thorntail/microprofile/pom.xml, projects-to-be-tested/vertx/simplest/src/main/java/org/eclipse/jkube/integrationtests/vertx/simplest/SimplestEmbedded.java, projects-to-be-tested/vertx/simplest/src/main/resources/vertx-default-jul-logging.properties, projects-to-be-tested/webapp/wildfly/pom.xml
Webapp tests can be run concurrently
Increased number of parallel threads for OpenShift, it seems to work quite well.
Removed order constraints for some of the test-cases
=> fix: webapp tests can be run concurrently

.github/workflows/e2e-tests.yml, it/src/test/java/org/eclipse/jkube/integrationtests/maven/BaseMavenCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/maven/MavenInvocationResult.java, it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcDockerModeITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarmK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarmOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/windows/WindowsITCase.java
Provided common method to retrieve logs.
Streams for stdout (log) are always flushed and closed.
=> fix: Test log retrieval unified

.github/workflows/e2e-tests.yml
- This version no longer removes Docker Daemon shipped with GH
environment. Run time should improve.
=> chore: Bump actions-setup-minikube to v2.0.0

.github/workflows/e2e-tests.yml
Upgrade `manusa/actions-setup-minikube` + `manusa/actions-setup-openshift` to the latest version.
Removes the following warnings caused by [CVE-2020-15228](https://github.com/actions/toolkit/security/advisories/GHSA-mfwh-5m23-j46w):
```
Warning: The `set-env` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
Warning: The `add-path` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
Relates to:
- https://github.com/manusa/actions-setup-minikube/issues/22
- …
=> chore: Upgrade actions-setup-minikube to v2.0.1 + -openshift to v1.1.2

it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJar.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarOcITCase.java, pom.xml
Upgraded both bootable JAR Maven plugin and WildFly.
Removed workaround for the relative path that has been fixed in bootable JAR starting 2.0.0.Final.
Signed-off-by: JF Denise jdenise@redhat.com
=> Fix for Issue #441, Upgrade integ-tests to use WildFly JAR 2 Final release.

.github/workflows/e2e-tests.yml
Port of https://github.com/fabric8io/kubernetes-client/pull/2553 to install JKube for all CI runs and cache the generated artifacts.
There shouldn't be any performance gain. Main reason is to allow tests to fail fast in case there are problems when installing JKube (we are getting many issues when downloading artifacts from maven central).
=> fix: CI fail-fast, install JKube and persist in ActionsCache

it/pom.xml, it/src/main/java/org/eclipse/jkube/integrationtests/gradle/JKubeGradleRunner.java, it/src/main/java/org/eclipse/jkube/integrationtests/jupiter/api/extension/GradleExtension.java, it/src/main/java/org/eclipse/jkube/integrationtests/jupiter/api/extension/RegistryExtension.java, pom.xml
The gradle extensions has an initial clean that is used
to download the dependencies so that later goals can be run
offline. This method wasn't updating the JKube version
with the provided system property.
=> feat: gradle global clean runs with JKube provided version

it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java
Fix https://github.com/jkubeio/jkube-integration-tests/issues/183. Somehow, printing the character '–' is killing the test and the whole test suite is marked as succeed but should be failing.
=> fix: Fix service assertion when the response content contains the '–' character

it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java, it/src/test/java/org/eclipse/jkube/integrationtests/dockerfile/SimpleK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/dsl/DslK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/dsl/DslOcGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLiberty.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/na7ive/QuarkusNativeK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/Quarkus.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/CustomResourceApp.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/Thorntail.java, it/src/test/java/org/eclipse/jkube/integrationtests/vertx/Vertx.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/Jetty.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFly.java, it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJar.java
Now that we're removing ExposeEnricher, there is no need to verify
whether generated Service contains `expose: true` label.
Related to https://github.com/eclipse/jkube/pull/1447
=> fix : Remove `assertExpose()` from ServiceAssertion

.github/workflows/e2e-tests.yml, .github/workflows/license-check.yml, .github/workflows/smoke-tests.yml, .github/workflows/windows-tests.yml
Related to https://github.com/eclipse/jkube/issues/1767
Set content write to read in GitHub workflows in order to limit permissions granted to GitHub token used in workflows
=> ci : Modify default permissions granted to GITHUB_TOKEN in workflows

.github/workflows/e2e-tests.yml, .github/workflows/license-check.yml, .github/workflows/smoke-tests.yml, .github/workflows/windows-tests.yml
+ Add [Harden Runner](https://github.com/step-security/harden-runner) E2E Tests, Smoke Tests and License GitHub actions. This action is only applicable to Ubuntu based workflows, so it doesn't work for Windows actions.
- I've commented out Harden Runner action declaration for OpenShift E2E tests because it's declaration seems to cause problems with setting up OpenShift cluster (even in `audit` mode).
+ Use latest commit SHA for Harden Runner
+ Pin all GitHub action steps to full length commit SHA, as directed in [GitHub docs](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
=> ci : Add Harden Runner GitHub action GitHub Action workflows

.github/workflows/e2e-tests.yml
Related to #243 
Reverts https://github.com/jkubeio/jkube-integration-tests/pull/241 
The latest update of actions/cache seems to be causing issues in E2E test runs. Looks like some bug has been introduced (linked in the issue comment).
Reverting to the previous version of actions/cache, for now, to see if it actually fixes the issue.
=> chore (deps) : revert actions/cache bump to latest revision (#243)

.github/workflows/e2e-tests.yml
Fix #243 
Upgrade actions/cache to latest revision that contains fix related to zstd
=> chore (deps) : bump actions/cache to `69d9d449aced6a2ede0bc19182fadc3a0a42d2b0` revision (#243)

it/src/test/java/org/eclipse/jkube/integrationtests/dsl/DslK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/dsl/DslOcGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfigITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/windows/WindowsITCase.java
Related to eclipse/jkube#1369
eclipse/jkube#2036 removes trailing classifier
suffixes from generated Helm Archives. It also changes the default
location where Helm Archive is generated. Update E2E tests to accomodate
this change.
=> test : Update Helm archive path in Helm related assertions

it/src/main/java/org/eclipse/jkube/integrationtests/docker/DockerUtils.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfigfatjar/ZeroConfigFatJar.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfigfatjar/ZeroConfigFatJarK8sITCase.java, pom.xml, projects-to-be-tested/maven/dockerfile/simple/pom.xml, projects-to-be-tested/maven/spring/complete/pom.xml, projects-to-be-tested/maven/spring/complete/src/main/jkube/k8s/deployment.yml, projects-to-be-tested/maven/spring/crd/pom.xml, projects-to-be-tested/maven/spring/helm-config/pom.xml, projects-to-be-tested/maven/spring/multi-profile/pom.xml, projects-to-be-tested/maven/spring/zero-config-fatjar/pom.xml, projects-to-be-tested/maven/spring/zero-config-fatjar/src/main/java/org/eclipse/jkube/integrationtests/springboot/zeroconfigfatjar/ZeroConfigFatJarApplication.java, projects-to-be-tested/maven/spring/zero-config-fatjar/src/main/java/org/eclipse/jkube/integrationtests/springboot/zeroconfigfatjar/ZeroConfigFatJarResource.java, projects-to-be-tested/maven/spring/zero-config/pom.xml
Related to https://github.com/eclipse/jkube/pull/2309
+ Remove unused variable
+ Update image list assertions to verify layer folders instead of the fat jar
+ Updated all spring test projects to use `spring.version` constant instead of inheriting version from dependencyManagement
+ Add `zero-config-fatjar` integration test spring project that will use `spring-boot.fat-jar.version` (2.3.9.RELEASE). Till this release, spring boot generated fat jars by default.
=> test : Update Spring boot tests for layered jar changes

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerITCase.java, projects-to-be-tested/maven/spring/complete/pom.xml
Related to https://github.com/eclipse/jkube/issues/2379
It should pass once https://github.com/eclipse/jkube/pull/2413 gets merged.
Add E2E test for verifying OpenShift's Docker build with Spring Boot layered jar changes to verify layers are not flattened during S2I Docker build.
=> test : Add OpenShift Docker build strategy IT case for Spring Boot Zero Config layered jar

.mvn/wrapper/maven-wrapper.properties
Required by #350 
```
The plugin io.openliberty.tools:liberty-maven-plugin:3.9 requires Maven version 3.8.6
```
https://github.com/jkubeio/ci uses Maven 3.8.8 which should be fine
=> deps: bump Maven wrapper to 3.9.5

.github/workflows/e2e-tests.yml
Resolves an issue where the github action build failed during the `Build JKube` step due to the inability to download Gradle. This fix enables downloads from githubusercontent.com, resolving the download issue.
```
[info] Downloading Gradle 7.6.2...
Error: [ERROR] Internal error: java.lang.IllegalStateException: Couldn't download Gradle 7.6.2: Connection refused (Connection refused) -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.IllegalStateException: Couldn't download Gradle 7.6.2
at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:121)
at org.apache.maven.cli.MavenCli.execute (MavenCli.java:9[63](https://github.com/jkubeio/jkube-integration-tests/actions/runs/6826073585/job/18587132317?pr=354#step:8:64))
at org.apache.maven.cli.MavenCli.doMain …
```
=> fix(build-jkube): allow downloads from githubusercontent.com for Gradle download

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerITCase.java
This was removed in https://github.com/eclipse/jkube/pull/2437 
Update CompleteOcDockerITCase with respect to this change.
=> test : Remove ENTRYPOINT assertion from CompleteOcDockerITCase

it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/Quarkus.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusOcITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusOcTraceEnabledITCase.java, pom.xml, projects-to-be-tested/maven/quarkus/rest-trace-logging-enabled/pom.xml, projects-to-be-tested/maven/quarkus/rest-trace-logging-enabled/src/main/java/org/eclipse/jkube/integrationtests/quarkus/rest/CoolApplicationWithTraceEnabled.java, projects-to-be-tested/maven/quarkus/rest-trace-logging-enabled/src/main/java/org/eclipse/jkube/integrationtests/quarkus/rest/CoolApplicationWithTraceEnabledResource.java, projects-to-be-tested/maven/quarkus/rest-trace-logging-enabled/src/main/java/org/eclipse/jkube/integrationtests/quarkus/rest/CoolApplicationWithTraceEnabledService.java
Related to https://github.com/eclipse/jkube/issues/2211
+ Add QuarkusOcTraceEnabledITCase to test suite which verifies
openshift maven plugin goals with `org.slf4j.simpleLogger.defaultLogLevel`
property set to trace
+ Add new test project `maven/quarkus/rest-trace-logging-enabled` for
testing abovementioned integration test
=> test : Add test to verify OpenShift trace logging works

pom.xml
Reates to: 
- https://github.com/eclipse-jkube/jkube/pull/3190
- https://github.com/eclipse-jkube/jkube/issues/2911
- https://github.com/eclipse-jkube/jkube/issues/2381
=> deps: bump karaf from 4.4.4 to 4.4.6 (Java 21 support)

it/src/test/java/org/eclipse/jkube/integrationtests/webapp/tomcat/TomcatJavaeeWithWebappsDirK8sITCase.java
Relates to: 
- https://github.com/eclipse-jkube/jkube/pull/3190
- https://github.com/eclipse-jkube/jkube/issues/2911
- https://github.com/eclipse-jkube/jkube/issues/2381
=> fix(tomcat): testJavaEENodePortResponseError compatible with newer and older tomcat images

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfig.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfigOcITCase.java
Related to eclipse/jkube#2666
Add e2e tests for these goals:
- `k8s:helm-install`
- `k8s:helm-uninstall`
- `oc:helm-install`
- `oc:helm-uninstall`
=> test : Add E2E tests for Helm Install and Uninstall functionality

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/layeredjardisabled/LayeredJarDisabled.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/layeredjardisabled/LayeredJarDisabledOcDockerITCase.java, pom.xml, projects-to-be-tested/maven/spring/complete/pom.xml, projects-to-be-tested/maven/spring/layered-jar-disabled/pom.xml, projects-to-be-tested/maven/spring/layered-jar-disabled/src/main/java/org/eclipse/jkube/integrationtests/springboot/layeredjardisabled/LayeredJarDisabledApplication.java, projects-to-be-tested/maven/spring/layered-jar-disabled/src/main/java/org/eclipse/jkube/integrationtests/springboot/layeredjardisabled/LayeredJarDisabledResource.java
Related to https://github.com/eclipse-jkube/jkube/issues/3420
Currently, CompleteOcDockerITCase and CompleteOcDockerLayersDisabledITCase use shared project. This causes problems when these projects are run concurrently as one test overwrites build directory (fat jar) that might be currently getting used by other test (the latter one uses legacy fat jar).
+ Move CompleteOcDockerLayerDisabledITCase to a different package and make
it use a different test project.
+ Update `jkube.version` to `1.18-SNAPSHOT`
=> test : Move `CompleteOcDockerLayerDisabledITCase` to a different package and make it use a different test project.

.github/workflows/e2e-crc-okd-tests.yml
Add a nightly build workflow for OKD 4.14.0 for running Fabric8 Kubernetes Client E2E tests.
=> ci : Add github action workflow for okd 4.14.0 cluster with crc

.github/workflows/e2e-crc-okd-tests.yml
Fix #392  
Somehow GitHub Action runner now no longer contains `virtiofsd` package
installed. 
+ Install  `virtiofsd`  explicitly to fix crc start failure.
+ Remove step to do `oc login`, kube context is already set to kubeadmin with `crc start`
=> ci : Install virtiofsd package while installing deps for crc

.github/workflows/e2e-crc-okd-tests.yml
GitHub is rolling out Ubuntu 24.04 on it's runners, sometimes runner os is selected  as 22.04 (where `virtiofsd` package required by CRC is already installed), sometimes it's 24.04 (where `virtiofsd` package is not installed)
Add a conditional `if` statement to install it only in case of 24.04
=> ci : Install virtiofsd only when runner os is Ubuntu 24.04

it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sGradleITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigK8sITCase.java, it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfigfatjar/ZeroConfigFatJarK8sITCase.java
Relates to https://github.com/eclipse-jkube/jkube/issues/3623
=> fix: accurately count copy dir statements
