- it/src/test/java/org/eclipse/jkube/integrationtests/zeroconfig/SpringBoot.java
Relates to https://github.com/manusa/fmp-integration-tests/commit/08fa911a871d2fd5db006ec3f98eb5f2a1036224
and the changes needed to fix the failing test
> fix: assert condition for pod deletion checks delete timestamp

- .github/workflows/integration-tests.yml
- pom.xml
- projects-to-be-tested/quarkus/native/pom.xml
- projects-to-be-tested/quarkus/rest/pom.xml
- projects-to-be-tested/spring-boot/complete/pom.xml
- projects-to-be-tested/spring-boot/multi-profile/pom.xml
- projects-to-be-tested/spring-boot/zero-config/pom.xml
- projects-to-be-tested/thorntail/microprofile/pom.xml
- projects-to-be-tested/vertx/simplest/pom.xml
- projects-to-be-tested/webapp/zero-config/pom.xml
> refactor: renamed maven plugins

- pom.xml
Signed-off-by: anandkrsingh <ansingh@redhat.com>
This pr updates kubernetes-client version to latest i.e 4.9.0
> kubernetes-client version changed to latest

- it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLiberty.java
- it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyOcITCase.java
- pom.xml
- projects-to-be-tested/openliberty/rest/pom.xml
- projects-to-be-tested/openliberty/rest/src/main/java/org/eclipse/jkube/integrationtests/openliberty/rest/RestApplication.java
- projects-to-be-tested/openliberty/rest/src/main/java/org/eclipse/jkube/integrationtests/openliberty/rest/RestEndpoint.java
- projects-to-be-tested/openliberty/rest/src/main/liberty/config/server.xml
This PR adds E2E test for openliberty Rest, solves [issue](https://github.com/eclipse/jkube/issues/137)
Fixes https://github.com/eclipse/jkube/issues/137
> E2E: OpenLiberty tests

- .github/workflows/e2e-tests.yml
verifies: manusa/actions-setup-minikube#7
> feat: Minikube tests run in v1.18.2

- it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarm.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarmK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildflyswarm/WildFlySwarmOcITCase.java
- pom.xml
- projects-to-be-tested/wildflyswarm/rest/pom.xml
- projects-to-be-tested/wildflyswarm/rest/src/main/java/org/swarm/wildfly/HelloWildfly.java
- projects-to-be-tested/wildflyswarm/rest/src/main/webapp/index.html
This PR Solves (ISSUE)[https://github.com/eclipse/jkube/issues/156] 
e2e test cases added for WildFly-Swarm sample-application
> WildFly-Swarm e2e test cases 

- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfig.java
fix port not ready problem in #42
> fix: webapp.ZeroConfig service port assertion waits for port to be ready

- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFly.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcDockerModeITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcITCase.java
- pom.xml
- projects-to-be-tested/webapp/wildfly/pom.xml
- projects-to-be-tested/webapp/wildfly/src/main/webapp/index.html
This PR Will add E2E test of Webapp Wildfly for k8s|oc-s2i|oc-docker modes.
> Webapp Wildfly e2e test 

- it/src/test/java/org/eclipse/jkube/integrationtests/assertions/KubernetesClientAssertion.java
- it/src/test/java/org/eclipse/jkube/integrationtests/assertions/ServiceAssertion.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJar.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarOcITCase.java
- pom.xml
- projects-to-be-tested/wildfly-jar/microprofile/pom.xml
- projects-to-be-tested/wildfly-jar/microprofile/src/main/java/org/eclipse/jkube/integrationtests/wildfly/microprofile/MicroProfileApplication.java
- projects-to-be-tested/wildfly-jar/microprofile/src/main/java/org/eclipse/jkube/integrationtests/wildfly/microprofile/MicroProfileResource.java
- projects-to-be-tested/wildfly-jar/microprofile/src/main/jkube/k8s/deployment.yml
- projects-to-be-tested/wildfly-jar/microprofile/src/main/jkube/oc/deploymentconfig.yml
Integration tests for openshift and kubernetes,
Signed-off-by: JF Denise <jdenise@redhat.com>
> Fix for issue eclipse#283, Add support for WildFly Bootable JAR, integration tests

- it/src/test/java/org/eclipse/jkube/integrationtests/maven/BaseMavenCase.java
It no longer checks service name using startsWith which may collide
when tests run concurrently on projects with multiple profiles (namely Spring Boot Complete).
> fix: Delete service assertion checks exact name for service

- .github/workflows/e2e-tests.yml
chore: Bump Minikube and Kubernetes Versions
> chore: Bump Minikube and Kubernetes Versions

- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJar.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarOcITCase.java
- pom.xml
- projects-to-be-tested/wildfly-jar/microprofile/pom.xml
- projects-to-be-tested/wildfly-jar/microprofile/src/main/jkube/k8s/deployment.yml
- projects-to-be-tested/wildfly-jar/microprofile/src/main/jkube/oc/deploymentconfig.yml
Signed-off-by: JF Denise jdenise@redhat.com
> Adjust WildFly Bootable JAR to slim server and default system options

- it/pom.xml
- it/src/test/java/org/eclipse/jkube/integrationtests/karaf/Karaf.java
- it/src/test/java/org/eclipse/jkube/integrationtests/karaf/KarafK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/karaf/KarafOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyOcITCase.java
- pom.xml
- projects-to-be-tested/karaf/camel-log/pom.xml
- projects-to-be-tested/karaf/camel-log/src/main/java/org/eclipse/jkube/integrationtests/karaf/camel/log/OrderGenerator.java
- projects-to-be-tested/karaf/camel-log/src/main/resources/OSGI-INF/blueprint/camel-log.xml
- projects-to-be-tested/karaf/camel-log/src/main/resources/assembly/etc/org.ops4j.pax.logging.cfg
- projects-to-be-tested/karaf/camel-log/src/main/resources/data/order1.xml
- projects-to-be-tested/karaf/camel-log/src/main/resources/data/order2.xml
- projects-to-be-tested/karaf/camel-log/src/main/resources/data/order3.xml
- projects-to-be-tested/karaf/camel-log/src/main/resources/data/order4.xml
- projects-to-be-tested/karaf/camel-log/src/main/resources/data/order5.xml
Signed-off-by: anandrkskd <anandrkskd@gmail.com>
Fixes [#254](https://github.com/eclipse/jkube/issues/254)
> E2E test for karaf-camel-log

- pom.xml
- projects-to-be-tested/wildfly-jar/microprofile/pom.xml
Fixes problems related to WildFly org.jboss.universe downloads
> fix: Use latest WildFly versions in wildfly-jar project

- it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/Quarkus.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfigITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfig.java
- it/src/test/java/org/eclipse/jkube/integrationtests/windows/WindowsITCase.java
https://github.com/eclipse/jkube/pull/608
> fix: Helm assertions comply with new apiVersion field

- it/src/test/java/org/eclipse/jkube/integrationtests/karaf/KarafK8sITCase.java
Required fixes after https://github.com/eclipse/jkube/pull/678
> feat: Karaf includes Jolokia Port

- it/src/test/java/org/eclipse/jkube/integrationtests/RequireK8sVersionAtLeast.java
- it/src/test/java/org/eclipse/jkube/integrationtests/RequireK8sVersionAtLeastCondition.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/CustomResourceApp.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/CustomResourceK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/CustomResourceOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/v1beta1/Framework.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/v1beta1/FrameworkSpec.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/crd/v1beta1/FrameworkStatus.java
- pom.xml
- projects-to-be-tested/spring-boot/crd/pom.xml
- projects-to-be-tested/spring-boot/crd/src/main/java/org/eclipse/jkube/quickstart/springboot/crd/CustomResourceApplication.java
- projects-to-be-tested/spring-boot/crd/src/main/java/org/eclipse/jkube/quickstart/springboot/crd/FrameworkResource.java
- projects-to-be-tested/spring-boot/crd/src/main/jkube/default-cluster-admin-crb.yml
- projects-to-be-tested/spring-boot/crd/src/main/jkube/framework-crd.yml
- projects-to-be-tested/spring-boot/crd/src/main/jkube/quarkus-cr.yml
- projects-to-be-tested/spring-boot/crd/src/main/jkube/spring-boot-cr.yml
- projects-to-be-tested/spring-boot/crd/src/main/jkube/vertx-cr.yml
Add an integration test to verify Custom Resource integration works as
expected with Kubernetes and OpenShift Maven Plugins
Related to https://github.com/eclipse/jkube/issues/1130
> Add E2E test for Spring Boot with Custom Resource

- .github/workflows/smoke-tests.yml
Related to https://github.com/eclipse/jkube/issues/1088
> chore : Add Automated smoke test pipeline for release

- .github/workflows/smoke-tests.yml
Related to https://github.com/eclipse/jkube/issues/1088
> fix : revert to Java 11 from Java 17 in Smoke test pipeline

- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/tomcat/Tomcat.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/tomcat/TomcatJakartaeeK8sITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/tomcat/TomcatJavaeeK8sITCase.java
- pom.xml
- projects-to-be-tested/maven/webapp/tomcat-jakartaee/pom.xml
- projects-to-be-tested/maven/webapp/tomcat-jakartaee/src/main/java/org/eclipse/jkube/tests/samples/HelloWorld.java
- projects-to-be-tested/maven/webapp/tomcat-jakartaee/src/main/webapp/WEB-INF/web.xml
- projects-to-be-tested/maven/webapp/tomcat-jakartaee/src/main/webapp/index.html
- projects-to-be-tested/maven/webapp/tomcat-javaeelegacy/pom.xml
- projects-to-be-tested/maven/webapp/tomcat-javaeelegacy/src/main/java/org/eclipse/jkube/tests/samples/HelloWorld.java
- projects-to-be-tested/maven/webapp/tomcat-javaeelegacy/src/main/webapp/WEB-INF/web.xml
- projects-to-be-tested/maven/webapp/tomcat-javaeelegacy/src/main/webapp/index.html
fix https://github.com/eclipse/jkube/issues/1477
> feat: Adding k8s integration tests for Tomcat JakartaEE and legacy JavaEE projects

- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyK8sWatchITCase.java
Add a test to verify `jkube.watch.mode=copy` scenario in JettyK8sWatchITCase
> test : Add test case in JettyK8sWatchITCase for watchMode=copy

- README.md
- it/pom.xml
- it/src/test/java/org/eclipse/jkube/integrationtests/Tags.java
- it/src/test/java/org/eclipse/jkube/integrationtests/dsl/DslOcGradleITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/karaf/KarafOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/openliberty/OpenLibertyOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/quarkus/rest/QuarkusOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteOcDockerLayersDisabledITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/helmconfig/HelmConfigITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/multiprofile/MultiProfileITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/watch/Watch.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/watch/WatchOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcGradleITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/zeroconfig/ZeroConfigOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/thorntail/ThorntailOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/vertx/VertxOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/jetty/JettyOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcDockerModeITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/wildfly/WildFlyOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/webapp/zeroconfig/ZeroConfigOcITCase.java
- it/src/test/java/org/eclipse/jkube/integrationtests/wildfly/jar/WildflyJarOcITCase.java
Relates to:
- https://github.com/fabric8io/kubernetes-client/issues/5545
> feat: OpenShiftOSCI tag

- pom.xml
Relates to https://github.com/eclipse/jkube/issues/2708
> fix: Spring Boot Watch test works

- .github/workflows/build-jkube.yml
- .github/workflows/e2e-tests.yml
Relates to https://github.com/fabric8io/kubernetes-client/issues/5545
> ci: reusable build-jkube workflow

- it/src/test/java/org/eclipse/jkube/integrationtests/springboot/complete/CompleteK8sJibITCase.java
Relates to https://github.com/eclipse-jkube/jkube/issues/2098
> feat: jib image build creates a jib-image.tar
